# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1d33df84afde82d27c1c9ca4fce23a5894aa7df7a96066f1bca21a66eaf5f14c50e15bbc440a7abcc6b96e01954cc1c034b9db0ff50d56c0c1b11c2d5d6bbf7d

test:
  secret_key_base: affe3483c0e6c730e916434b2994a977fe1ae989a1f59c1ee9120a562a2f1f9ef383297a6c3a5307d15e442b896a21fa6a8f4ecd3e182ab980f47e21bd87d17d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
